name: CI/CD Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t hackathon-landing -f docker/Dockerfile.dev .
    
    - name: Test Docker container
      run: |
        docker run -d -p 8080:80 hackathon-landing
        sleep 5
        curl --fail http://localhost:8080 || exit 1
        
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag hackathon-landing ${{ secrets.DOCKER_HUB_USERNAME }}/hackathon-landing:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hackathon-landing:latest
